### ISSUE TITLE
Build error stdout maxBuffer exceeded

### ISSUE THREAD

**Issue by roberthgodoy** [apache/cordova-ios#1057]
### Issue Type

- [ ] Bug Report
- [ ] Feature Request
- [x] Support Question
.
### Command or Code

```
➜  enterprise-name-app git:(1.0.60) cordova build ios --verbose
No scripts found for hook "before_build".
Executing script found in plugin branch-cordova-sdk for hook "before_prepare": plugins/branch-cordova-sdk/src/scripts/hooks/beforePrepare.js
Checking config.xml and package.json for saved platforms that haven't been added to the project
Config.xml and package.json platforms are the same. No pkg.json modification.
Package.json and config.xml platforms are different. Updating config.xml with most current list of platforms.
PlatformApi successfully found for platform ios
Checking for saved plugins that haven't been added to the project
Checking for any plugins added to the project that have not been installed in ios platform
No differences found between plugins added to project and installed in ios platform. Continuing...
Generating platform-specific config.xml from defaults for iOS at /Users/usermac/ENTERPRISENAME/enterprise-name-app/platforms/ios/Enterprise Name/config.xml
Merging project's config.xml into platform-specific iOS config.xml
Merging and updating files from [www, platforms/ios/platform_www] to platforms/ios/www
  copy  www/.DS_Store platforms/ios/www/.DS_Store (updated file)
  copy  www/app/auth/forgot-password/forgot-password.html platforms/ios/www/app/auth/forgot-password/forgot-password.html (updated file)
Current launch storyboard CDVLaunchScreen
Not changing launch storyboard setting in info plist.
Wrote out iOS Bundle Version "1.0.59" to /Users/usermac/ENTERPRISENAME/enterprise-name-app/platforms/ios/Enterprise Name/Enterprise Name-Info.plist
No need to update build settings for launch storyboard support.
Set IPHONEOS_DEPLOYMENT_TARGET to "11.0".
Did not update build settings for launch storyboard support.
iOS Product Name has not changed (still "Enterprise Name")
Updating icons at platforms/ios/Enterprise Name/Images.xcassets/AppIcon.appiconset/
  copy  resources/ios/icon/icon-1024.png platforms/ios/Enterprise Name/Images.xcassets/AppIcon.appiconset/icon-1024.png (updated file)
  copy  resources/ios/splash/Default~iphone.png platforms/ios/Enterprise Name/Images.xcassets/LaunchImage.launchimage/Default~iphone.png (updated file)
Updating launch storyboard images at platforms/ios/Enterprise Name/Images.xcassets/LaunchStoryboard.imageset/
  copy  resources/ios/splash/Default@2x~universal~anyany.png platforms/ios/Enterprise Name/Images.xcassets/LaunchStoryboard.imageset/Default@2x~universal~anyany.png (updated file)
Updating Storyboard image set contents.json
This app does not have additional resource files defined
Prepared iOS project successfully
Executing script found in hooks directory for hook "after_prepare": hooks/after_prepare/010_add_platform_class.js
Running command: /Users/usermac/ENTERPRISENAME/enterprise-name-app/hooks/after_prepare/010_add_platform_class.js /Users/usermac/ENTERPRISENAME/enterprise-name-app
add to body class: platform-ios
Command finished with error code 0: /Users/usermac/ENTERPRISENAME/enterprise-name-app/hooks/after_prepare/010_add_platform_class.js /Users/usermac/ENTERPRISENAME/enterprise-name-app
Executing script found in plugin branch-cordova-sdk for hook "after_prepare": plugins/branch-cordova-sdk/src/scripts/hooks/afterPrepare.js
Executing script found in plugin cordova-plugin-add-swift-support for hook "after_prepare": plugins/cordova-plugin-add-swift-support/src/add-swift-support.js
Executing script found in plugin cordova-plugin-facebook4 for hook "after_prepare": plugins/cordova-plugin-facebook4/scripts/after_prepare.js
No scripts found for hook "before_compile".
Reading build config file: /Users/usermac/ENTERPRISENAME/enterprise-name-app/build.json
stdout maxBuffer exceeded
Error: stdout maxBuffer exceeded
    at Socket.onChildStdout (child_process.js:328:14)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:246:13)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at Pipe.onread (net.js:607:20)
```

### Version information

cordova -v = 9.0.0 (cordova-lib@9.0.1)
node -v = 8.11.1
xcode-select -v = 2384
xcode version = 12.2
cordova-ios = 5.1.1

## Checklist

- [x] I searched for already existing GitHub issues about this
- [ ] I updated all Cordova tooling to their most recent version
- [x] I included all the necessary information above

**Comment by roberthgodoy** [comment]
I solved this problem by updating node version to 10.13 and cordova-ios version to 6.1.1

**Comment by thislooksfun** [comment]
If anyone else runs across this while having to maintain a legacy ionic+cordova codebase, try updating the first line of `listEmulatorBuildTargets` (in `platforms/ios/cordova/lib/list-emulator-build-targets`) to be `return Q.nfcall(exec, 'xcrun simctl list --json', { maxBuffer: 20*1024*1024 })`.
