### ISSUE TITLE
[ERROR] An error occurred while running subprocess cordova.

### ISSUE THREAD

**Issue by Freeman-Dogbo** [apache/cordova-ios#1096]
Bonjour, voilà environ 2 semaines je ne trouve pas de solution à mon problème j'ai besoin d'aide svp

C:\Users\LENOVO\ProjetIonic>ionic cordova platform add android
> cordova.cmd platform add android
C:\Users\LENOVO\AppData\Roaming\npm\node_modules\cordova\node_modules\windows-release\node_modules\execa\index.js:347
                throw err;
                ^

Error: Command failed: powershell (Get-CimInstance -ClassName Win32_OperatingSystem).caption
ou externe, un programme ex�cutable ou un fichier de commandes.

    at makeError (C:\Users\LENOVO\AppData\Roaming\npm\node_modules\cordova\node_modules\windows-release\node_modules\execa\index.js:174:9)
    at Function.module.exports.sync (C:\Users\LENOVO\AppData\Roaming\npm\node_modules\cordova\node_modules\windows-release\node_modules\execa\index.js:338:15)
    at windowsRelease (C:\Users\LENOVO\AppData\Roaming\npm\node_modules\cordova\node_modules\windows-release\index.js:39:19)
    at osName (C:\Users\LENOVO\AppData\Roaming\npm\node_modules\cordova\node_modules\os-name\index.js:39:18)
    at new Insight (C:\Users\LENOVO\AppData\Roaming\npm\node_modules\cordova\node_modules\insight\lib\index.js:37:13)
    at new RelentlessInsight (C:\Users\LENOVO\AppData\Roaming\npm\node_modules\cordova\src\telemetry.js:31:1)
    at Object.<anonymous> (C:\Users\LENOVO\AppData\Roaming\npm\node_modules\cordova\src\telemetry.js:39:15)
    at Module._compile (node:internal/modules/cjs/loader:1092:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1121:10)
    at Module.load (node:internal/modules/cjs/loader:972:32) {
![forum d'aide](https://user-images.githubusercontent.com/76484013/113649024-38071a00-967d-11eb-8bf8-fe1cbfaa0eba.JPG)
![forum d'aide](https://user-images.githubusercontent.com/76484013/113649087-55d47f00-967d-11eb-9ddf-1315f9a13244.JPG)

  code: 1,
  stdout: '',
  stderr: "'powershell' n'est pas reconnu en tant que commande interne\r\n" +
    'ou externe, un programme ex�cutable ou un fichier de commandes.\r\n',
  failed: true,
  signal: null,
  cmd: 'powershell (Get-CimInstance -ClassName Win32_OperatingSystem).caption',
  timedOut: false
}
[ERROR] An error occurred while running subprocess cordova.

        cordova.cmd platform add android exited with exit code 1.

        Re-running this command with the --verbose flag may provide more information.

**Comment by breautek** [comment]
Moving this to `cordova-cli` repo, as it appears to have to do with the `cordova` main executable... definitely not related to `cordova-ios`.

Can you also fill out the version information that you removed from the template?
- OS Version
- Node Version
- NPM Version
- Cordova Version

Also can you confirm if this occurs without using the Ionic cli? Install cordova directly and create a cordova project...

```
npm install cordova -g
cordova create testProject
cd testProject
cordova platform add android
```

Thanks
