### ISSUE TITLE
Tests fail to find cordova-common

### ISSUE THREAD

**Issue by regiMario** [apache/cordova-ios#462]
While working on PR 461 i tried to run the tests and got the following error:
```
[mario@mac13dev ~/github/cordova-ios]$ npm test

> cordova-ios@5.0.0-dev test /Users/mario/github/cordova-ios
> npm run unit-tests && npm run test:component && npm run objc-tests && npm run e2e-tests


> cordova-ios@5.0.0-dev unit-tests /Users/mario/github/cordova-ios
> jasmine --config=tests/spec/unit.json

DEPRECATION: Setting throwOnExpectationFailure directly on Env is deprecated, please use the oneFailurePerSpec option in `configure`
DEPRECATION: Setting randomizeTests directly is deprecated, please use the random option in `configure`
internal/modules/cjs/loader.js:582
    throw err;
    ^

Error: Cannot find module 'cordova-common'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
    at Function.Module._load (internal/modules/cjs/loader.js:506:25)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/mario/github/cordova-ios/tests/spec/unit/Api.spec.js:22:21)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 4
npm ERR! cordova-ios@5.0.0-dev unit-tests: `jasmine --config=tests/spec/unit.json`
npm ERR! Exit status 4
npm ERR! 
npm ERR! Failed at the cordova-ios@5.0.0-dev unit-tests script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?
npm ERR! Test failed.  See above for more details.
```

```
[mario@mac13dev ~/github/cordova-ios]$ npm -g list --depth=0
/usr/local/lib
├── cordova@8.1.2
├── cordova-common@3.0.0
├── ios-deploy@1.9.4
├── jasmine@3.3.0
└── npm@6.4.1
[mario@mac13dev ~/github/cordova-ios]$ node --version
v10.13.0
```

This was on macosx 10.13. It's not clear to me whether this is a cordova-ios, general cordova or a setup bug of mine. I was advised to file a an issue regarding this so here it is.

**Comment by janpio** [comment]
Thanks, I edited your issue a bit to make it more readable (triple ` to format a code block instead of just a line).

**Comment by brodybits** [comment]
Please do the following:

>
* Ensure that you are on the master branch and have the latest changes from
GitHub
* Remove generated artifacts (node_modules and package-lock.json)
* Ensure that git status --ignored shows no changes
* Do npm install
* Do npm run unit-tests

Then it should be possible for npm test to work.

**Comment by brodybits** [comment]
On Tue, Nov 13, 2018, 7:50 AM Chris Brody <notifications@github.com> wrote:

> Please do the following:
>

I will try it myself in the next 30-60 minutes.

>

**Comment by brodybits** [comment]
You need to install the pod tool for that test to pass. It may not be so urgent since it is covered by Travis CI.

**Comment by brodybits** [comment]
I think we can close this. Please report if you encounter any more issues with npm test.
