### ISSUE TITLE
`file://` in allow-navigation crashes on iOS

### ISSUE THREAD

**Issue by ankon** [apache/cordova-ios#539]
# Bug Report

## Problem

Using `<allow-navigation href="file://"></allow-navigation>` crashes `parseWhitelistUrlForATS` on iOS.

~~~~
TypeError: Cannot read property 'indexOf' of null
    at parseWhitelistUrlForATS (.../.cordova/platforms/ios/cordova/lib/prepare.js:1056:27)
    at .../.cordova/platforms/ios/cordova/lib/prepare.js:982:23
    at Array.reduce (<anonymous>)
    at processAccessAndAllowNavigationEntries (.../.cordova/platforms/ios/cordova/lib/prepare.js:973:10)
    at writeATSEntries (.../.cordova/platforms/ios/cordova/lib/prepare.js:1099:16)
    at updateProject (.../.cordova/platforms/ios/cordova/lib/prepare.js:215:15)
    at .../.cordova/platforms/ios/cordova/lib/prepare.js:59:20
    at _fulfilled (.../.cordova/node_modules/q/q.js:854:54)
    at .../.cordova/node_modules/q/q.js:883:30
    at Promise.promise.promiseDispatch (.../.cordova/node_modules/q/q.js:816:13)"
~~~~

### What is expected to happen?

"Nothing", as the setting is the default.

### What does actually happen?

An error that `indexOf` isn't a function on undefined :)

## Information

https://github.com/apache/cordova-ios/blob/5e688ca4ddf698fad5d10185f7583dec49abcfe1/bin/templates/scripts/cordova/lib/prepare.js#L1051-L1068

As per the documentation the value `file://` is the default (https://cordova.apache.org/docs/en/latest/reference/cordova-plugin-whitelist/), but when using that value `!retObject.HostName` is true-ish, but there is no `href.pathname`.

### Version information

cordova-ios 5.0.0.

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by purplecabbage** [comment]
I have added a potential fix for the crash.  In the mean time, there is no benefit to adding 'file://' to your whitelist since it is already allowed.  If you feel you must, then please use 'file://*'
