### ISSUE TITLE
Unable to install iOS platform

### ISSUE THREAD

**Issue by jakubdolejs** [apache/cordova-ios#607]
# Bug Report

## Problem
When I go to add iOS platform to a newly-created Cordova project I get an error.

### What is expected to happen?
Cordova should add iOS platform

### What does actually happen?
Command fails with a NPM error

## Information

Transcript of the shell session:
```
cordova platform add ios
Using cordova-fetch for cordova-ios@^5.0.0
Failed to fetch platform cordova-ios@^5.0.0
Probably this is either a connection problem, or platform spec is incorrect.
Check your connection and platform name/version/URL.
Error: npm: Command failed with exit code 1 Error output:
npm ERR! Unexpected end of JSON input while parsing near '...p":"^0.0.26"},"_hasSh'

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/redacted/.npm/_logs/2019-04-29T19_28_11_053Z-debug.log
```

Debug log contents:

```
0 info it worked if it ends with ok
1 verbose cli [ '/opt/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   'cordova-ios@^5.0.0',
1 verbose cli   '--production',
1 verbose cli   '--save' ]
2 info using npm@6.8.0
3 info using node@v10.15.3
4 verbose npm-session f751d091bf0a3560
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 304 https://registry.npmjs.org/cordova-ios 108ms (from cache)
8 silly fetchPackageMetaData error for cordova-ios@^5.0.0 Unexpected end of JSON input while parsing near '...p":"^0.0.26"},"_hasSh'
9 timing stage:rollbackFailedOptional Completed in 0ms
10 timing stage:runTopLevelLifecycles Completed in 143ms
11 verbose stack SyntaxError: Unexpected end of JSON input while parsing near '...p":"^0.0.26"},"_hasSh'
11 verbose stack     at JSON.parse (<anonymous>)
11 verbose stack     at parseJson (/usr/local/lib/node_modules/npm/node_modules/json-parse-better-errors/index.js:7:17)
11 verbose stack     at consumeBody.call.then.buffer (/usr/local/lib/node_modules/npm/node_modules/node-fetch-npm/src/body.js:96:50)
11 verbose stack     at process._tickCallback (internal/process/next_tick.js:68:7)
12 verbose cwd /Users/redacted/CdvTest
13 verbose Darwin 18.5.0
14 verbose argv "/opt/local/bin/node" "/usr/local/bin/npm" "install" "cordova-ios@^5.0.0" "--production" "--save"
15 verbose node v10.15.3
16 verbose npm  v6.8.0
17 error Unexpected end of JSON input while parsing near '...p":"^0.0.26"},"_hasSh'
18 verbose exit [ 1, true ]
```

### Command or Code

```cordova platform add ios```

(Android platform adds fine)

### Environment, Platform, Device

- MacOS Mojave 10.14.4

### Version information

- Cordova CLI version 9.0.0 (cordova-lib@9.0.1)
- NPM version 6.8.0
- Node version v10.15.3

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by janpio** [comment]
`npm cache verify` is happy?

**Comment by jakubdolejs** [comment]
Seems to be:

**Comment by janpio** [comment]
Strange:

```
7 http fetch GET 304 https://registry.npmjs.org/cordova-ios 108ms (from cache)
8 silly fetchPackageMetaData error for cordova-ios@^5.0.0 Unexpected end of JSON input while parsing near '...p":"^0.0.26"},"_hasSh'
```

I interpret this that the package data it has in the cache seems to be corrupted somehow. Might try to clear the cache or reinstall `npm` maybe.

**Comment by jakubdolejs** [comment]
Thank you @janpio. You're right. Something with the cache. I set the NPM cache using `npm install --cache /tmp/npm-cache` and I was able to install the platform.

**Comment by janpio** [comment]
Yay!

**Comment by kuttikrishnankodoth** [comment]
I had the similar issue and npm install --cache /tmp/npm-cache fixed it.
but iam not sure what it does though :)
