### ISSUE TITLE
plugin podspec with no config leads to TypeError

### ISSUE THREAD

**Issue by brodybits** [apache/cordova-ios#913]
# Bug Report

## Problem

While working on a new SQLite plugin version, I would like to use sqlite3 pod in a very simple manner. My understanding of <https://cordova.apache.org/docs/en/latest/plugin_ref/spec.html#podspec-ios> is that it should be enough to add the following lines to `plugin.xml` within `<platform name="ios">`:

```xml
    <podspec>
      <pods>
        <pod name="sqlite3" spec="~> 3.32.3" />
      </pods>
    </podspec>
```

### What is expected to happen?

I should be able to use the Cordova CLI to add my new plugin and then do `cordova platform add ios@latest`.

### What does actually happen?

When I do `cordova platform add ios@latest`, it fails with the following nonsense error output:

```
Failed to install 'cordova-plugin-sqlite-batch-connection-manager-core': TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at /Users/brodybits/dev/cordova-plugin-sqlite-batch-connection-manager-core/demo/platforms/ios/cordova/Api.js:374:20
    at Array.forEach (<anonymous>)
    at Api.addPodSpecs (/Users/brodybits/dev/cordova-plugin-sqlite-batch-connection-manager-core/demo/platforms/ios/cordova/Api.js:355:18)
    at /Users/brodybits/dev/cordova-plugin-sqlite-batch-connection-manager-core/demo/platforms/ios/cordova/Api.js:278:29
    at _fulfilled (/Users/brodybits/dev/cordova-plugin-sqlite-batch-connection-manager-core/demo/node_modules/q/q.js:854:54)
    at /Users/brodybits/dev/cordova-plugin-sqlite-batch-connection-manager-core/demo/node_modules/q/q.js:883:30
    at Promise.promise.promiseDispatch (/Users/brodybits/dev/cordova-plugin-sqlite-batch-connection-manager-core/demo/node_modules/q/q.js:816:13)
    at /Users/brodybits/dev/cordova-plugin-sqlite-batch-connection-manager-core/demo/node_modules/q/q.js:624:44
    at runSingle (/Users/brodybits/dev/cordova-plugin-sqlite-batch-connection-manager-core/demo/node_modules/q/q.js:137:13)
```

Quick workaround is to add an empty config element like this:

```xml
    <podspec>
      <config>
      </config>
      <pods>
        <pod name="sqlite3" spec="~> 3.32.3" />
      </pods>
    </podspec>
```

## Information

Reproduction plugin is here: <https://github.com/brodybits/cordova-plugin-sqlite-batch-connection-manager-core-unstable-0x/tree/reproduce-cordova-ios-podspec-issue>

From a quick look I think this issue is lurking in cordova-common.

For some reason this does not seem to be an issue with cordova-osx.

### Command or Code

```
cordova plugin add github:brodybits/cordova-plugin-sqlite-batch-connection-manager-core-unstable-0x#reproduce-cordova-ios-podspec-issue
cordova platform add ios@latest
```

### Version information

cordova --version: 9.0.0 (cordova-lib@9.0.1)
Cordova platform: iOS
Cordova plugin: see above

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by NiklasMerz** [comment]
When I run the example commands I get a different error:

```
Using cordova-fetch for cordova-ios@latest
Adding ios project...
Creating Cordova project for the iOS platform:
	Path: platforms/ios
	Package: io.cordova.hellocordova
	Name: HelloCordova
iOS project created with cordova-ios@6.1.1
Installing "cordova-plugin-sqlite-batch-connection-manager-core" for ios
Error during processing of action! Attempting to revert...
Failed to install 'cordova-plugin-sqlite-batch-connection-manager-core': CordovaError: Uh oh!
"/home/niklas/Projekte/podspecissue/plugins/cordova-plugin-sqlite-batch-connection-manager-core/dist-dependencies/SQLiteBatchCore.m" not found!
    at copyFile (/home/niklas/Projekte/podspecissue/platforms/ios/cordova/lib/plugman/pluginHandlers.js:309:36)
    at copyNewFile (/home/niklas/Projekte/podspecissue/platforms/ios/cordova/lib/plugman/pluginHandlers.js:335:5)
    at installHelper (/home/niklas/Projekte/podspecissue/platforms/ios/cordova/lib/plugman/pluginHandlers.js:259:13)
    at install (/home/niklas/Projekte/podspecissue/platforms/ios/cordova/lib/plugman/pluginHandlers.js:34:13)
    at ActionStack.process (/home/niklas/Projekte/podspecissue/node_modules/cordova-common/src/ActionStack.js:56:25)
    at PluginManager.doOperation (/home/niklas/Projekte/podspecissue/node_modules/cordova-common/src/PluginManager.js:112:24)
    at PluginManager.addPlugin (/home/niklas/Projekte/podspecissue/node_modules/cordova-common/src/PluginManager.js:142:21)
    at Api.addPlugin (/home/niklas/Projekte/podspecissue/platforms/ios/cordova/Api.js:254:10)
    at handleInstall (/home/niklas/.nvm/versions/node/v10.16.0/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:561:10)
    at /home/niklas/.nvm/versions/node/v10.16.0/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:344:28
Uh oh!
"/home/niklas/Projekte/podspecissue/plugins/cordova-plugin-sqlite-batch-connection-manager-core/dist-dependencies/SQLiteBatchCore.m" not found!

```
